CREATE TABLE IF NOT EXISTS loyalty (
    id INT auto_increment PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    type_id TINYINT NOT NULL,
    manager_id INT DEFAULT 1,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    expired DATETIME DEFAULT CURRENT_TIMESTAMP,
    data TEXT,
    active TINYINT DEFAULT 1
);